<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-SigningService-c5e37ee9-846d-41f6-8eca-6e8e2c625ee1</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BouncyCastle.Cryptography" Version="2.6.2" />
    <PackageReference Include="MassTransit.RabbitMQ" Version="8.3.4" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.1" />
    <PackageReference Include="System.Security.Cryptography.Pkcs" Version="10.0.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Logic\Logic.csproj" />
    <ProjectReference Include="..\Storage\Storage.csproj" />
    <ProjectReference Include="..\FileStorage\FileStorage.csproj" />
    <ProjectReference Include="..\NewDiplom\Contracts.csproj" />
    <ProjectReference Include="..\Models\Models.csproj" />
    <ProjectReference Include="..\MessageContracts\MessageContracts.csproj" />
  </ItemGroup>
</Project>
